config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
       :controllers => {omniauth_callbacks: "omniauth_callbacks"},
       :controllers => { confirmations: "confirmations" }

  resources :playlists do
    resources :tracks
  end

  post '/users/update_invite_user_status' => 'users#update_invite_user_status'
  root 'welcome#landing'
  get 'main/index'

   get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email
   patch '/users/:id/add_email' => 'users#add_email'

end

app/models/track.rb
class Track < ActiveRecord::Base

  belongs_to :playlist
  has_many :likes

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @playlist = Playlist.find(params[:playlist_id])
    @tracks = @playlist.tracks
  end

  def new
    @track = Track.new
  end

  def create
    @track = Playlist.find(params[:playlist_id]).tracks.new(:title => params[:track][:title], :artist => params[:track][:artist], :url=> params[:track][:url])

    respond_to do |format|
      if @track.save
        format.html { redirect_to playlist_tracks_path(params[:playlist_id]), notice: 'Track was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
end

app/views/tracks/index.html.erb
<h1>Playlist <%= @playlist.name %> </h1>
<table>
   <th>Tracks<th>
  <%- unless @tracks.nil? %>
  <%- @tracks.each do |obj| %>
   <tr>
      <td>
        Title : <%= obj.title%>
        Artist : <%= obj.artist%>
        URL : <%= obj.url%>
      </td>
   </tr>
  <%- end %>
  <%- end %>
</table>

<%= link_to 'New Track', new_playlist_track_path(params[:playlist_id]) %>

app/views/tracks/new.html.erb
<%= form_for @track, url: {action: "create", controller: "tracks"} do |f| %>
<div class="panel-heading">
  <b>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </b>

  <b>
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </b>

  <b>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </b>
    <div class="actions"><%= f.submit 'Save' %></div>
</div>
<%- end %>