config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
       :controllers => {omniauth_callbacks: "omniauth_callbacks"},
       :controllers => { confirmations: "confirmations" }

  resources :playlists do
    resources :tracks
  end

  post '/users/update_invite_user_status' => 'users#update_invite_user_status'
  root 'welcome#landing'
  get 'main/index'

   get '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email
   patch '/users/:id/add_email' => 'users#add_email'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  belongs_to :user
  has_many :followers
  has_many :tracks

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
      @playlists = User.find(current_user.id).playlists
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = current_user.playlists.new(:name => params[:playlist][:name])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlists_path, notice: 'Playlist was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
end

app/views/playlists/index.html.erb
<h1>Playlist</h1>

<table>
   <th>Playlist<th>
  <%- unless @playlists.nil? %>
  <%- @playlists.each do |obj| %>
   <tr>
      <td>
        <%= link_to obj.name, playlist_tracks_path(obj.id)%>
      </td>
   </tr>
  <%- end %>
  <%- end %>
</table>

<%= link_to 'New Playlist', new_playlist_path(params[:id]) %>

app/views/playlists/new.html.erb
<%= form_for @playlist, url: {action: "create", controller: "playlists"} do |f| %>
<div class="panel-heading">
  <b>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </b>
    <div class="actions"><%= f.submit 'Save' %></div>
</div>
<%- end %>